export const receivedAssessmentData = [
  {
    idAssessment: '55550453040',
    reviewerName: 'Carlos Doe',
    userName: 'carlos_doe_10',
    email: 'carlos@email.com',
    assessmentDate: '28-10-2023',
    assessmentScores: [{
      id: 'aB3cD7eF',
      type: 'Ideas',
      quality: 'Fair',
      rate: 1,
    },
    {
      id: '9GhI2jKl',
      type: 'Content',
      quality: 'Excellent',
      rate: 5,
    }],
    problemStep: 'Staff',
    feedback: 'This is working really well',
  },
  {
    idAssessment: '55550453042',
    reviewerName: 'John Smith',
    userName: 'john_smith_23',
    email: 'john@email.com',
    assessmentDate: '30-10-2023',
    assessmentScores: [{
      id: 'M4nO8pQr',
      type: 'Ideas',
      quality: 'Good',
      rate: 5,
    },
    {
      id: 'X5tU6vWx',
      type: 'Content',
      quality: 'Excellent',
      rate: 5,
    }],
    problemStep: 'Training',
    feedback: 'Great progress!',
  },
  {
    idAssessment: '55550453048',
    reviewerName: 'Emily Johnson',
    userName: 'emily_j',
    email: 'emily@email.com',
    assessmentDate: '29-10-2023',
    assessmentScores: [{
      id: 'PqW0uVwX',
      type: 'Ideas',
      quality: null,
      rate: null,
    },
    {
      id: 'ZabC12DE',
      type: 'Content',
      quality: null,
      rate: null,
    }],
    problemStep: 'Peers',
    feedback: 'Needs improvement in certain areas.',
  },
  {
    idAssessment: '55550453050',
    reviewerName: 'Sarah Brown',
    userName: 'sarah_brown_45',
    email: 'sarah@email.com',
    assessmentDate: '31-10-2023',
    assessmentScores: [{
      id: 'Yz123456',
      type: 'Ideas',
      quality: 'Good',
      rate: 3,
    },
    {
      id: 'L7iR9oSt',
      type: 'Content',
      quality: 'Excellent',
      rate: 5,
    }],
    problemStep: 'Self',
    feedback: 'Excellent work, keep it up!',
  },
];

export const givenAssessmentData = receivedAssessmentData.map(assessment => ({
  ...assessment,
  learnerName: assessment.reviewerName,
}));
