name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Nodejs
      uses: actions/setup-node@v4
# Because of node 18 bug (https://github.com/nodejs/node/issues/47563), Pinning node version 18.15 until the next release of node
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci

    - name: Verify No Uncommitted Changes
      run: make validate-no-uncommitted-package-lock-changes

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Run Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Send failure notification
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: email-smtp.us-east-1.amazonaws.com
        server_port: 465
        username: ${{ secrets.EDX_SMTP_USERNAME }}
        password: ${{ secrets.EDX_SMTP_PASSWORD }}
        subject: Upgrade python requirements workflow failed in ${{github.repository}}
        to: masters-grades@edx.org
        from: github-actions <github-actions@edx.org>
        body: Upgrade python requirements workflow in ${{github.repository}} failed!
          For details see "github.com/${{ github.repository }}/actions/runs/${{ github.run_id
          }}"
